const { SlashCommandBuilder, AttachmentBuilder } = require('discord.js');
const { getDb } = require('../../database/connection');
const fortniteAPI = require('../../services/fortnite-api');
const aiService = require('../../services/openai-service');
const { createErrorEmbed } = require('../../utils/embeds');
const config = require('../../config');
const logger = require('../../utils/logger');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('highlight-card')
        .setDescription('Generate a personalized highlight card with AI (Elite only)')
        .addStringOption(option =>
            option.setName('username')
                .setDescription('Epic username (defaults to linked account)')
                .setRequired(false)),

    async execute(interaction) {
        // Check elite access only
        const member = interaction.member;
        const hasElite = member.roles.cache.has(config.roles.elite);
        
        if (!hasElite) {
            return interaction.reply({
                embeds: [createErrorEmbed(
                    'Elite Required', 
                    'This exclusive command requires 👑 Elite tier only.\nUse `/claim elite` with 100 invites or `/membership` for purchase options.'
                )],
                ephemeral: true
            });
        }

        await interaction.deferReply();

        try {
            const username = interaction.options.getString('username');
            
            // Get stats
            let stats;
            let displayName;
            
            if (username) {
                const response = await fortniteAPI.getStats(username);
                stats = response.data?.stats?.all?.overall;
                displayName = response.data?.account?.name || username;
            } else {
                const db = getDb();
                const user = db.prepare('SELECT epic_username FROM users WHERE discord_id = ?')
                    .get(interaction.user.id);
                
                if (!user?.epic_username) {
                    return interaction.editReply({
                        embeds: [createErrorEmbed('No Linked Account', 'Please provide a username or link your Epic account first.')]
                    });
                }
                
                const response = await fortniteAPI.getStats(user.epic_username);
                stats = response.data?.stats?.all?.overall;
                displayName = response.data?.account?.name || user.epic_username;
            }

            if (!stats) {
                return interaction.editReply({
                    embeds: [createErrorEmbed('No Stats', 'Could not retrieve stats for highlight card.')]
                });
            }

            // Get locker items for showcase
            const db = getDb();
            const locker = db.prepare('SELECT cosmetic_id FROM lockers WHERE user_id = ? LIMIT 3')
                .all(interaction.user.id);

            const cosmetics = [];
            for (const item of locker) {
                try {
                    const cosmetic = await fortniteAPI.getCosmeticById(item.cosmetic_id);
                    if (cosmetic.data) cosmetics.push(cosmetic.data);
                } catch (e) {}
            }

            // Generate AI highlight
            const highlight = await aiService.generateHighlightCard(stats, cosmetics);

            // Create embed card
            const { EmbedBuilder } = require('discord.js');
            
            const embed = new EmbedBuilder()
                .setColor(0xFFD700)
                .setTitle(`🏆 ${displayName}'s Highlight Card`)
                .setThumbnail(interaction.user.displayAvatarURL({ dynamic: true }))
                .addFields(
                    { name: '🏅 Wins', value: (stats.wins || 0).toString(), inline: true },
                    { name: '🎯 K/D', value: (stats.kd || 0).toFixed(2), inline: true },
                    { name: '📈 Win Rate', value: `${(stats.winRate || 0).toFixed(1)}%`, inline: true }
                )
                .setDescription(highlight)
                .setFooter({ text: 'Generated by ValorFN AI | Elite Exclusive' })
                .setTimestamp();

            // Add featured cosmetic image
            if (cosmetics.length > 0 && cosmetics[0].images?.featured) {
                embed.setImage(cosmetics[0].images.featured);
            }

            // Add showcase cosmetics
            if (cosmetics.length > 0) {
                const showcase = cosmetics.map(c => `• ${c.name}`).join('\n');
                embed.addFields({
                    name: '🎭 Featured Cosmetics',
                    value: showcase,
                    inline: false
                });
            }

            await interaction.editReply({ embeds: [embed] });
        } catch (error) {
            logger.error('Highlight card error:', error);
            await interaction.editReply({
                embeds: [createErrorEmbed('Error', 'Failed to generate highlight card. Please try again.')]
            });
        }
    }
};
